site:
  title: Across
  start_page: across::index
content:
  sources:
  - url: https://github.com/ForeachOS/ax-docs-across.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-platform.git
    branches: develop
    start_path: docs/guides
  - url: https://github.com/ForeachOS/ax-docs-platform.git
    branches: develop
    start_path: docs/migration
  - url: https://github.com/ForeachOS/ax-docs-dynamic-forms-module.git
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-admin-web-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-bootstrap-ui-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-entity-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-ldap-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-security-acl-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-web-cms-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-security-module.git
    branches: master
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-oauth2-module.git
    branches: master
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-user-module.git
    branches: master
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-hibernate-jpa-module.git
    branches: master
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-across-autoconfigure.git
    branches: master
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-debug-web-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-application-info-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-file-manager-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-logging-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-ehcache-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-properties-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-mobile-module.git
    branches: develop
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-batch-module.git
    branches: develop
    start_path: docs
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  destinations:
  - provider: archive
    path: build/docs-across-site.zip
asciidoc:
  attributes:
    spring-boot-docs: "https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/"
    spring-framework-docs: "https://docs.spring.io/spring/docs/4.3.17.RELEASE/spring-framework-reference/htmlsingle/"
    ax-initializr-url: "http://start-across.foreach.be/"