site:
  title: Across
  start_page: across::index
content:
  sources:
  - url: https://github.com/ForeachOS/ax-docs-across.git
    branches: antora
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-platform.git
    branches: develop
    start_path: docs/guides
  - url: https://github.com/ForeachOS/ax-docs-platform.git
    branches: develop
    start_path: docs/migration
  - url: https://github.com/ForeachOS/ax-docs-dynamic-forms-module.git
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  destinations:
  - provider: archive
    path: build/docs-across-site.zip