site:
  title: Across
  start_page: 2.1.1@across::index
content:
  sources:
  - url: https://github.com/ForeachOS/ax-docs-across.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-platform.git
    branches: [master]
    start_path: docs/guides
  - url: https://github.com/ForeachOS/ax-docs-platform.git
    branches: [master,develop-*]
    start_path: docs/migration
  - url: https://github.com/ForeachOS/ax-docs-dynamic-forms-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-admin-web-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-bootstrap-ui-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-entity-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-ldap-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-security-acl-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-web-cms-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-security-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-oauth2-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-user-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-hibernate-jpa-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-across-autoconfigure.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-debug-web-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-application-info-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-file-manager-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-logging-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-ehcache-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-properties-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-mobile-module.git
    branches: [master,develop,develop-*]
    start_path: docs
  - url: https://github.com/ForeachOS/ax-docs-spring-batch-module.git
    branches: [master,develop,develop-*]
    start_path: docs
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  destinations:
  - provider: archive
    path: build/docs-across-site.zip
asciidoc:
  attributes:
    spring-boot-docs: "https://docs.spring.io/spring-boot/docs/1.5.14.RELEASE/reference/htmlsingle/"
    spring-framework-docs: "https://docs.spring.io/spring/docs/4.3.18.RELEASE/spring-framework-reference/htmlsingle/"
    ax-initializr-url: "http://start-across.foreach.be/"
    url-AcrossHibernateModule: "https://across.foreach.be/modules/AcrossHibernateModule"
    url-AdminWebModule: "https://across.foreach.be/modules/AdminWebModule"
    url-ApplicationInfoModule: "https://across.foreach.be/modules/ApplicationInfoModule"
    url-BootstrapUiModule: "https://across.foreach.be/modules/BootstrapUiModule"
    url-DebugWebModule: "https://across.foreach.be/modules/DebugWebModule"
    url-EntityModule: "https://across.foreach.be/modules/EntityModule"
    url-OAuth2Module: "https://across.foreach.be/modules/OAuth2Module"
    url-SpringSecurityModule: "https://across.foreach.be/modules/SpringSecurityModule"
    url-SpringSecurityAclModule: "https://across.foreach.be/modules/SpringSecurityAclModule"
    url-UserModule: "https://across.foreach.be/modules/UserModule"